### ISSUE TITLE
COA Error When Page Served Over HTTP

### ISSUE THREAD

**Issue by RaniSputnik** [Jaaap/SQRL#7]
I'm writing a SQRL server and I noticed that, when testing locally over HTTP, the extension fails to log me in with a COA error. There are two places in `background.js` where we swap the sqrl protocol for https.

1. https://github.com/Jaaap/SQRL/blob/master/background.js#L157
2. https://github.com/Jaaap/SQRL/blob/master/background.js#L508

If we instead swapped in the window protocol, then the extension could work for a page served over http. The question is, would we actually want to _fix_ this given that SQRL transactions should all be made over HTTPS anyway?

From my side, I'm going to be changing my local development server to serve over https instead. Thanks for all your work on this extension!

**Comment by Jaaap** [comment]
Did you successfully switch to https on your local server?

**Comment by RaniSputnik** [comment]
I haven't done it yet, but I still plan to https://github.com/RaniSputnik/sqrl-go/issues/10.

Currently I'm using a modified version of the extension to get around the issue.

**Comment by Jaaap** [comment]
The last i heard about is from Steve was this:
https://www.grc.com/x/news.exe?cmd=article&group=grc.sqrl&item=17009
so i think we're supposed to go https-only.

**Comment by RaniSputnik** [comment]
Cool, sounds pretty definitive to me. I'll close this and work on a fix from my side.
