### ISSUE TITLE
Is Chrome Webstore version trustworthy?

### ISSUE THREAD

**Issue by t9999clint** [Jaaap/SQRL#9]
I found these in the Firefox and Chrome webstores, They seem to reference this site and GRC.com I just wanted to confirm with you guys if this is a trustworthy source before I installed it to my systems.

https://chrome.google.com/webstore/detail/sqrl/adfaiodpchglcmalaiifkcclimpffono
https://addons.mozilla.org/en-US/firefox/addon/sqrl/

You should probably also note if it's trustworthy or not on the readme to prevent further confusion with new users.

Thanks for your hardwork.

**Comment by Jaaap** [comment]
Yes they are.
DONE.

**Comment by t9999clint** [comment]
Excellent! That'll make things a lot easier for people to install.

**Comment by smw1218** [comment]
@Jaaap I had the same question and I think it's hard from the store listing to tell that this repo is the source for the extensions and that you are the developer. Could you add your real name to your github account? And maybe add the github link directly to the description. The Add-on info is a bit buried (especially on mobile)

**Comment by Jaaap** [comment]
I added the github link to the description.
